### ISSUE TITLE
Прапанова па паляпшэнні перакладу

### ISSUE THREAD

**Issue by user9435213451** [BusnjukAn/MA-XML-14-BELORUSSIAN#1]
![IMAGE 2023-10-10 21:16:56](https://github.com/BusnjukAn/MA-XML-14-BELORUSSIAN/assets/83395945/17e49f7b-c6f5-48a9-b85e-6b8e58a13c33)

Вітаю! На маю думку, было б лепей звычайнае "Не турбаваць" замест доўгага тэксту. Усё роўна не змяшчаецца.

![IMAGE 2023-10-10 21:29:14](https://github.com/BusnjukAn/MA-XML-14-BELORUSSIAN/assets/83395945/36f8eebf-9f02-4754-a737-1aa914e2156f)

Таксама ў наладах камеры: 
1 - няма перакладу
2 - не той сэнс. Правільней было б "Кантраляваць запісаны гук праз правадныя навушнікі, калі яны падключаны"

Дзякуй за Вашу працу! 

Device: Xiaomi 13 (Fuxi), Ver: 23.9.18

**Comment by BusnjukAn** [comment]
Дзякуй. Вось як вырашыў зрабіць https://github.com/BusnjukAn/MA-XML-14-BELORUSSIAN/commit/e1a03df10ed417b766f25cd87dfe3b8fbd7fd958
